name: Deploy to server

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: appleboy/ssh-action@v1.2.1
        name: Deploy to server
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd ${{secrets.PROJECT_DIR}}
            git fetch --all
            git reset --hard origin/main

            /home/hoangkmhd190/.nvm/versions/node/v16.16.0/bin/npm install --force
            /home/hoangkmhd190/.nvm/versions/node/v16.16.0/bin/npm run build


