name: Deploy to server

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - uses: appleboy/ssh-action@v1.2.1
        name: Deploy to server
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd ${{secrets.PROJECT_DIR}}
            git fetch --all
            git reset --hard origin/main
            export NVM_DIR="$HOME/.nvm"
            source $NVM_DIR/nvm.sh

            nvm install 18
            nvm use 18

            cd ${{secrets.PROJECT_DIR}}
            git fetch --all
            git reset --hard origin/main

            npm install --force
            npm run build

            

